spring:
  application:
    name: ms-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: Postgres1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: configserver:http://localhost:8888
server:
  port: 8082
management:
  tracing:
    sampling:
      probability: 1.0
